// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {frontend} from '../models';

export function ApproveHostKeyUpdate(arg1:string,arg2:boolean):Promise<void>;

export function CacheMonitoringResult(arg1:main.SSHSession,arg2:string,arg3:string):Promise<void>;

export function CancelSFTPTransfer(arg1:string):Promise<void>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function CheckWSLAvailable():Promise<boolean>;

export function CleanupSessionMetrics(arg1:string):Promise<void>;

export function Close():Promise<void>;

export function CloseFileExplorerSession(arg1:string):Promise<void>;

export function CloseMonitoringSession(arg1:main.SSHSession):Promise<void>;

export function CloseSSHSession(arg1:main.SSHSession):Promise<void>;

export function CloseShell(arg1:string):Promise<void>;

export function CloseTab(arg1:string):Promise<void>;

export function CloseWindow():Promise<void>;

export function ConfigGet(arg1:string):Promise<main.SettingValue>;

export function ConfigSet(arg1:string,arg2:main.SettingValue):Promise<void>;

export function CreateDefaultProfiles():Promise<void>;

export function CreateMonitoringSession(arg1:main.SSHSession,arg2:main.SSHConfig):Promise<void>;

export function CreateProfile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.Profile>;

export function CreateProfileAPI(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.Profile>;

export function CreateProfileFolder(arg1:string,arg2:string,arg3:string):Promise<main.ProfileFolder>;

export function CreateProfileFolderAPI(arg1:string,arg2:string,arg3:string):Promise<main.ProfileFolder>;

export function CreateProfileFolderWithParentID(arg1:string,arg2:string,arg3:string):Promise<main.ProfileFolder>;

export function CreateProfileFolderWithParentIDAPI(arg1:string,arg2:string,arg3:string):Promise<main.ProfileFolder>;

export function CreateProfileWithFolderID(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.Profile>;

export function CreateProfileWithFolderIDAPI(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.Profile>;

export function CreateRemoteDirectory(arg1:string,arg2:string):Promise<void>;

export function CreateSSHSession(arg1:string,arg2:main.SSHConfig):Promise<main.SSHSession>;

export function CreateSSHSessionWithSize(arg1:string,arg2:main.SSHConfig,arg3:number,arg4:number):Promise<main.SSHSession>;

export function CreateTab(arg1:string,arg2:main.SSHConfig):Promise<main.Tab>;

export function CreateTabFromProfile(arg1:string):Promise<main.Tab>;

export function CreateVirtualFolder(arg1:string,arg2:string,arg3:string,arg4:main.VirtualFilter):Promise<main.VirtualFolder>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteProfileAPI(arg1:string):Promise<void>;

export function DeleteProfileFolder(arg1:string):Promise<void>;

export function DeleteProfileFolderAPI(arg1:string):Promise<void>;

export function DeleteProfileFolderWithContentsAPI(arg1:string):Promise<void>;

export function DeleteRemotePath(arg1:string,arg2:string):Promise<void>;

export function DeleteRemotePathAdvanced(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DeleteVirtualFolder(arg1:string):Promise<void>;

export function DownloadAndInstallUpdate(arg1:string):Promise<void>;

export function DownloadRemoteDirectory(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadRemoteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadRemoteFileWithProgress(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<void>;

export function DuplicateProfile(arg1:string):Promise<main.Profile>;

export function EnableAI(arg1:boolean):Promise<void>;

export function ExecuteMonitoringCommand(arg1:main.SSHSession,arg2:string):Promise<string>;

export function ExportMetrics(arg1:string):Promise<void>;

export function ForceDisconnectSSHSession(arg1:string):Promise<void>;

export function ForceDisconnectTab(arg1:string):Promise<void>;

export function GetAIConfig():Promise<main.AIConfig>;

export function GetAISupportedModels():Promise<Array<string>>;

export function GetActiveTab():Promise<main.Tab>;

export function GetActiveTabInfo():Promise<Record<string, any>>;

export function GetAvailableAIProviders():Promise<Array<string>>;

export function GetAvailableShells():Promise<Array<string>>;

export function GetAvailableShellsFormatted():Promise<Array<Record<string, string>>>;

export function GetCachedMonitoringResult(arg1:main.SSHSession,arg2:string):Promise<string|boolean>;

export function GetDefaultShell():Promise<string>;

export function GetFolderByID(arg1:string):Promise<main.ProfileFolder>;

export function GetFolderByIDAPI(arg1:string):Promise<main.ProfileFolder>;

export function GetMetricHistory(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetMetrics():Promise<main.ProfileMetrics>;

export function GetMetricsAPI():Promise<main.ProfileMetrics>;

export function GetOSInfo():Promise<Record<string, any>>;

export function GetPlatformInfo():Promise<Record<string, any>>;

export function GetPopularTags():Promise<Array<Record<string, any>>>;

export function GetPopularTagsAPI():Promise<Array<string>>;

export function GetProfile(arg1:string):Promise<main.Profile>;

export function GetProfileByID(arg1:string):Promise<main.Profile>;

export function GetProfileByIDAPI(arg1:string):Promise<main.Profile>;

export function GetProfileFolder(arg1:string):Promise<main.ProfileFolder>;

export function GetProfileTree():Promise<Array<main.ProfileTreeNode>>;

export function GetProfileTreeAPI():Promise<Array<main.ProfileTreeNode>>;

export function GetProfileUsageStats(arg1:string):Promise<Record<string, any>>;

export function GetProfilesByTag(arg1:string):Promise<Array<main.Profile>>;

export function GetProfilesByType(arg1:string):Promise<Array<main.Profile>>;

export function GetProfilesDirectory():Promise<string>;

export function GetRecentProfiles(arg1:number,arg2:number):Promise<Array<main.Profile>>;

export function GetRemoteFileContent(arg1:string,arg2:string):Promise<string>;

export function GetRemoteSystemStats(arg1:string):Promise<Record<string, any>>;

export function GetRemoteWorkingDirectory(arg1:string):Promise<string>;

export function GetShellsForUI():Promise<Array<Record<string, any>>>;

export function GetSystemMetadata():Promise<Record<string, any>>;

export function GetSystemStats():Promise<Record<string, any>>;

export function GetTabStatus(arg1:string):Promise<Record<string, any>>;

export function GetTabs():Promise<Array<main.Tab>>;

export function GetTopProfiles(arg1:number):Promise<Array<main.Profile>>;

export function GetUpdateRate(arg1:string):Promise<number>;

export function GetUsageTrends(arg1:number):Promise<Record<string, any>>;

export function GetVersionInfo():Promise<main.VersionInfo>;

export function GetVirtualFolderProfilesAPI(arg1:string):Promise<Array<main.Profile>>;

export function GetVirtualFolders():Promise<Array<main.VirtualFolder>>;

export function GetVirtualFoldersAPI():Promise<Array<main.VirtualFolder>>;

export function GetWSLDistributions():Promise<Array<main.WSLDistribution>>;

export function GetWSLInfo():Promise<Record<string, any>>;

export function GetWatcherStatus():Promise<Record<string, any>>;

export function GetWindowMaximizedState():Promise<boolean>;

export function Greet(arg1:string):Promise<string>;

export function InitSessionMetrics(arg1:string):Promise<void>;

export function InitializeFileExplorerSession(arg1:string):Promise<void>;

export function InitializeProfiles():Promise<void>;

export function IsAIEnabled():Promise<boolean>;

export function IsSessionClosed(arg1:string):Promise<boolean>;

export function IsWindowMaximized():Promise<boolean>;

export function ListRemoteFiles(arg1:string,arg2:string):Promise<Array<main.RemoteFileEntry>>;

export function LoadProfile(arg1:string):Promise<main.Profile>;

export function LoadProfileFolder(arg1:string):Promise<main.ProfileFolder>;

export function LoadProfiles():Promise<void>;

export function MaximizeWindow():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function MoveFolder(arg1:string,arg2:string):Promise<void>;

export function MoveFolderAPI(arg1:string,arg2:string):Promise<void>;

export function MoveProfile(arg1:string,arg2:string):Promise<void>;

export function MoveProfileByID(arg1:string,arg2:string):Promise<void>;

export function MoveProfileByIDAPI(arg1:string,arg2:string):Promise<void>;

export function ReconnectTab(arg1:string):Promise<void>;

export function RecordMetric(arg1:string,arg2:string,arg3:number):Promise<void>;

export function RecordStats(arg1:string,arg2:Record<string, any>):Promise<void>;

export function RenameRemotePath(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameTab(arg1:string,arg2:string):Promise<void>;

export function ReorderTabs(arg1:Array<string>):Promise<void>;

export function ResetMetrics():Promise<void>;

export function ResizeSSHSession(arg1:main.SSHSession,arg2:number,arg3:number):Promise<void>;

export function ResizeShell(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartApplication():Promise<void>;

export function RestartProfileWatcher():Promise<void>;

export function SaveProfile(arg1:main.Profile):Promise<void>;

export function SaveProfileFolder(arg1:main.ProfileFolder):Promise<void>;

export function SearchProfiles(arg1:string,arg2:Array<string>):Promise<Array<main.Profile>>;

export function SearchProfilesAPI(arg1:string,arg2:Array<string>):Promise<Array<main.Profile>>;

export function SelectDirectory():Promise<string>;

export function SelectFile(arg1:string,arg2:Array<frontend.FileFilter>):Promise<string>;

export function SelectFilesToUpload():Promise<Array<string>>;

export function SelectSSHPrivateKey():Promise<string>;

export function SelectSaveLocation(arg1:string):Promise<string>;

export function SendAIRequest(arg1:string):Promise<main.AIResponse>;

export function SetAIConfig(arg1:main.AIConfig):Promise<void>;

export function SetAIProvider(arg1:string):Promise<void>;

export function SetActiveTab(arg1:string):Promise<void>;

export function SetUpdateRate(arg1:string,arg2:number):Promise<void>;

export function ShowMessageDialog(arg1:string,arg2:string):Promise<void>;

export function StartMetricsAutoSave():Promise<void>;

export function StartProfileWatcher():Promise<void>;

export function StartSSHShell(arg1:main.SSHSession):Promise<void>;

export function StartShell(arg1:string,arg2:string):Promise<void>;

export function StartTabShell(arg1:string):Promise<void>;

export function StartTabShellWithSize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function StopProfileWatcher():Promise<void>;

export function TestAIConnection():Promise<Record<string, any>>;

export function ToggleFavoriteAPI(arg1:string):Promise<void>;

export function UpdateHostKey(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function UpdateProfile(arg1:main.Profile):Promise<void>;

export function UpdateProfileFolder(arg1:main.ProfileFolder):Promise<void>;

export function UpdateProfileTagsAPI(arg1:string,arg2:Array<string>):Promise<void>;

export function UpdateRemoteFileContent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateVirtualFolder(arg1:string,arg2:string,arg3:string,arg4:main.VirtualFilter):Promise<void>;

export function UploadFileContent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UploadRemoteFiles(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function WaitForSessionClose(arg1:string):Promise<void>;

export function WriteToSSHSession(arg1:main.SSHSession,arg2:string):Promise<void>;

export function WriteToShell(arg1:string,arg2:string):Promise<void>;
