// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckWSLAvailable() {
  return window['go']['main']['App']['CheckWSLAvailable']();
}

export function CloseShell(arg1) {
  return window['go']['main']['App']['CloseShell'](arg1);
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function GetAvailableShells() {
  return window['go']['main']['App']['GetAvailableShells']();
}

export function GetAvailableShellsFormatted() {
  return window['go']['main']['App']['GetAvailableShellsFormatted']();
}

export function GetCurrentDefaultShellSetting() {
  return window['go']['main']['App']['GetCurrentDefaultShellSetting']();
}

export function GetDefaultShell() {
  return window['go']['main']['App']['GetDefaultShell']();
}

export function GetOSInfo() {
  return window['go']['main']['App']['GetOSInfo']();
}

export function GetPlatformInfo() {
  return window['go']['main']['App']['GetPlatformInfo']();
}

export function GetShellsForUI() {
  return window['go']['main']['App']['GetShellsForUI']();
}

export function GetWSLDistributions() {
  return window['go']['main']['App']['GetWSLDistributions']();
}

export function GetWSLInfo() {
  return window['go']['main']['App']['GetWSLInfo']();
}

export function GetWindowMaximizedState() {
  return window['go']['main']['App']['GetWindowMaximizedState']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsSessionClosed(arg1) {
  return window['go']['main']['App']['IsSessionClosed'](arg1);
}

export function IsWindowMaximized() {
  return window['go']['main']['App']['IsWindowMaximized']();
}

export function MaximizeWindow() {
  return window['go']['main']['App']['MaximizeWindow']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function ResizeShell(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeShell'](arg1, arg2, arg3);
}

export function SetDefaultShell(arg1) {
  return window['go']['main']['App']['SetDefaultShell'](arg1);
}

export function ShowMessageDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowMessageDialog'](arg1, arg2);
}

export function StartShell(arg1, arg2) {
  return window['go']['main']['App']['StartShell'](arg1, arg2);
}

export function WaitForSessionClose(arg1) {
  return window['go']['main']['App']['WaitForSessionClose'](arg1);
}

export function WriteToShell(arg1, arg2) {
  return window['go']['main']['App']['WriteToShell'](arg1, arg2);
}
