// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckWSLAvailable():Promise<boolean>;

export function CloseShell(arg1:string):Promise<void>;

export function CloseWindow():Promise<void>;

export function GetAvailableShells():Promise<Array<string>>;

export function GetDefaultShell():Promise<string>;

export function GetPlatformInfo():Promise<Record<string, any>>;

export function GetWSLDistributions():Promise<Array<main.WSLDistribution>>;

export function GetWSLInfo():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function IsSessionClosed(arg1:string):Promise<boolean>;

export function IsWindowMaximized():Promise<boolean>;

export function MaximizeWindow():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function ResizeShell(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ShowMessageDialog(arg1:string,arg2:string):Promise<void>;

export function StartShell(arg1:string,arg2:string):Promise<void>;

export function WaitForSessionClose(arg1:string):Promise<void>;

export function WriteToShell(arg1:string,arg2:string):Promise<void>;
