// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckWSLAvailable() {
  return window['go']['main']['App']['CheckWSLAvailable']();
}

export function CloseShell(arg1) {
  return window['go']['main']['App']['CloseShell'](arg1);
}

export function GetAvailableShells() {
  return window['go']['main']['App']['GetAvailableShells']();
}

export function GetDefaultShell() {
  return window['go']['main']['App']['GetDefaultShell']();
}

export function GetPlatformInfo() {
  return window['go']['main']['App']['GetPlatformInfo']();
}

export function GetWSLDistributions() {
  return window['go']['main']['App']['GetWSLDistributions']();
}

export function GetWSLInfo() {
  return window['go']['main']['App']['GetWSLInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ResizeShell(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeShell'](arg1, arg2, arg3);
}

export function ShowMessageDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowMessageDialog'](arg1, arg2);
}

export function StartShell(arg1, arg2) {
  return window['go']['main']['App']['StartShell'](arg1, arg2);
}

export function WriteToShell(arg1, arg2) {
  return window['go']['main']['App']['WriteToShell'](arg1, arg2);
}
